### ISSUE TITLE
[Question] Change container credentials

### ISSUE THREAD

**Issue by JulienDecottignies** [Microsoft/nav-docker#238]
Hi,

Is it possible to change the container credentials ? 
My company policies asks me to regularly change my password. And then I have to deploy a new business central container, as I deployed with windows authentification.

So I want to know if it's possible to change the credentials informations of the container, in order to update them when I update my windows domain password.

It will be also usefull if I want to connect to the container when I'm outside of my domain.

Thanks !

**Comment by richardrobberse** [comment]
I think it creates a local user in the container with the windows credentials you've specified.
You could try to use the Set-LocalUser cmdlet to change the password as specified [here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.localaccounts/set-localuser?view=powershell-5.1)
I haven't tried this before, so please use it on a non-important container.

Another option could be to use NavUserPassword authentication so that the company policies do not apply.

**Comment by freddydk** [comment]
I think you should work on putting yourself in a position, where you can re-create the container.
In general, the containers should be replaceable easily if you end up in a situation where you need to backup a container or keep a container - you might be on the wrong path.
