### ISSUE TITLE
Azure Data Studio with NAV/D365BC on Docker

### ISSUE THREAD

**Issue by MatDDev** [Microsoft/nav-docker#279]
Hello Guys,

Is it possible to connect to SQL on Docker with Azure Data Studio? I found an article with information on how to connect to container database with SSMS, but I wonder if it's possible to do the same with Azure Data Studio? Did anyone try it?

Thanks!

**Comment by tfenster** [comment]
Yes, it works exactly the same. I've been using of for the last couple of months for 90% of my "SQL needs" as I usually am done with my task that way quicker than SSMS would even start :)

**Comment by tfenster** [comment]
Depending on your setup it might be even easier (mainly if you are using ssl or not). For me it looks like this for a container names cronus17cu14, because I have disabled ssl and enabled windows auth:

![image](https://user-images.githubusercontent.com/15346084/46939027-84051500-d065-11e8-9c8f-9c0e8962ae56.png)

![image](https://user-images.githubusercontent.com/15346084/46939070-a4cd6a80-d065-11e8-92d7-04b1e717a727.png)

But really, that depends on your setup and the way that Steven describes might very well be exactly correct for your needs

**Comment by MatDDev** [comment]
Many thanks! I will check settings and try to connect to database.
