### ISSUE TITLE
[Question] reverse proxy web client

### ISSUE THREAD

**Issue by kostenko** [Microsoft/nav-docker#283]
Hello, I have several Nav docker containers running inside a VM on Azure, and I'm trying (unsuccessfully) to set up Nginx as a reverse proxy to be able to open Nav web clients from the outside world using the hostname/public IP of the Azure VM.
I wonder if it requires any special configuration or if there is a guide on how to accomplish this not necessarily with Nginx?

I create containers using navcontainerhelper:
```
    New-NavContainer -accept_eula `
        -containerName $containerName ` // demo
        -auth Windows `
        -WebClientPort $webClientPort ` // 8080
        -credential $credential `
        -includeCSide `
        -licensefile $mylicense `
        -imageName $imageName `
        -updateHosts
```

my Nginx configuration is:
```
http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
    server {
        listen 80;

        location /demo/ {
          proxy_pass http://demo:8080/nav;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $remote_addr;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
```
The port 80 is open from Azure dashboard.

The only thing that happens with this set up is that when I open `http://myAzureHostname/demo` — it gets replaced with `http://myAzureHostname/nav`

Thanks

**Comment by freddydk** [comment]
Containernames cannot be used as instance names - you would have to do this with different webclientports for the different containers and then add -additionalparameters @("--publish thatport")

**Comment by kostenko** [comment]
Oh, so if I set WebClientPort to 8080, it's not exposed to the host but `-additionalparameters @("--publish 8080:8080")` will do that, so I can then proxy to it?

**Comment by freddydk** [comment]
WebClientPort set to 8080 will make it accessible ON the host. the additional parameter will then publish that port so that it is accessible from outside the host. I do not know what nginx does and whether you can do what you want, but you also have to set --env publicdnsname=<the public dnsname of the machine> and based on that, a configuration setting called publicWebClientUrl is calculated by adding the /nav to that publicdnsname - you might have to modify that as well.
Let me know if you make it work - it might be something other people can use as well.

**Comment by kostenko** [comment]
Thanks, Freddy, I'll try it tomorrow will get back to you.

**Comment by tfenster** [comment]
@kostenko we do something similar and have implemented it by setting up the publicDnsName as Freddy mentioned and then in AdditionalSetup.ps1 create a new Web Server Instance with the name we want. That way we have the same web client name internally ("behind" nginx) and externally ("before" nginx) which afaik is necessary because the WebClient otherwise will always redirect you to /nav. We tinkered a lot with rewrite rules but this in the end was the only stable solution we could come up with and it actually is quite easily implemented.

To give you an example: We have a NAV container called "cronus" and through the AdditionalSetup.ps1 we create a WebClient instance called "cronus" inside the container as well. With that we can do a simple nginx config like this

```
    location /cronus/ {
        proxy_pass http://cronus/cronus/;
    }
```

For your reference, our AdditionalSetup.ps1 looks like this 

```
$instance = $env:webInstanceName

if (!$restartingInstance -and ($instance -ne "")) {
    Write-Host "Creating NAV Web Server Instance $instance"
    New-NAVWebServerInstance -Server "localhost" `
                            -ClientServicesCredentialType $auth `
                            -ClientServicesPort 7046 `
                            -ServerInstance "NAV" `
                            -WebServerInstance $instance

    Remove-Item Env:\webInstanceName -Force
}
```

And when we run the container we give it an env param `webInstanceName=cronus`

If you happen to be at Directions next week, you might want to come by one of my Docker sessions where I'll either explain exactly that scenario directly as part of the session or we can have a discussion about it (and we need to discuss your avatar choice ;) )

**Comment by freddydk** [comment]
In a very near future it will be possible to define the Web Client instance name (Part of Business Central branding), which I guess will make life easier for you.

**Comment by tfenster** [comment]
Yes, then we could remove the custom AdditionalSetup script

**Comment by kostenko** [comment]
Thanks, guys, I didn't have a chance to try @tfenster solution before I left for vacation but it looks pretty clear and is exactly what I was looking for. I'll close the ticket and will write back in 3 weeks.
