### ISSUE TITLE
AllowNtlm is false in bconprem-master

### ISSUE THREAD

**Issue by tfenster** [Microsoft/nav-docker#336]
If I run a bconprem-master:w1 container and try to connect using the Windows Client with Win Auth, I get an error because the AllowNtlm setting is false in ClientUserSettings.config for the ClickOnce download. If I check the preview 5 DVD, the setting is still true as it was in all previous releases AFAIK. Is this by design?

**Comment by freddydk** [comment]
I don’t know, will check this.
Do note that the master branch now is targeting fall 2019 release as we have branched off for spring release.

Få Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: Tobias Fenster <notifications@github.com>
Sendt: Monday, March 25, 2019 10:52:29 AM
Til: Microsoft/nav-docker
Cc: Subscribed
Emne: [Microsoft/nav-docker] AllowNtlm is false in bconprem-master (#336)


If I run a bconprem-master:w1 container and try to connect using the Windows Client with Win Auth, I get an error because the AllowNtlm setting is false in ClientUserSettings.config for the ClickOnce download. If I check the preview 5 DVD, the setting is still true as it was in all previous releases AFAIK. Is this by design?

**Comment by freddydk** [comment]
For spring release - this works.
I have stopped building -master builds from fall release for now - will restart that after spring release.
please reopen if this remains a problem at that time.

**Comment by tfenster** [comment]
If someone needs a workaround until then, we have just added the following snippet in a copy of SetupClickOnce.ps1 [here](https://github.com/Microsoft/nav-docker/blob/9e1a01e1ef132ac822f91dd99be7de0d61592c9f/generic/Run/130/SetupClickOnce.ps1#L44) and put that file in the "my" folder. Seems to do the job
```
if ($Auth -eq "Windows") {
    $clientUserSettings.SelectSingleNode("//configuration/appSettings/add[@key='AllowNtlm']").value="true"
}
```
