### ISSUE TITLE
Outdating Containers

### ISSUE THREAD

**Issue by elweilando** [microsoft/nav-docker#378]
I try to start some containers and get the issue that the container image is over 90 days old.
Then I remove these containers with 
`docker stop NAME` 
and 
`docker rm NAME `
and 
`docker rmi IMAGE ID`

If I try to start the containers, the images will be downloaded again, but i receive the same issue again: "The container is over 90 days old".

How can I fix that?

REPOSITORY |TAG|IMAGE ID|CREATED| SIZE
----|----|----|----|----
microsoft/dynamics-nav | 2018-cu12-fi-ltsc2016 | ef54871df619 | 3 months ago | 18.1GB
microsoft/dynamics-nav | 2016-cu12-de-ltsc2016 | 869db40c22bb | 3 months ago | 16.5GB

**Comment by elweilando** [comment]
microsoft/dynamics-nav   2018-cu12-fi-ltsc2016   ef54871df619        3 months ago        18.1GB
microsoft/dynamics-nav   2016-cu12-de-ltsc2016   869db40c22bb        3 months ago        16.5GB

**Comment by freddydk** [comment]
Use mcr.microsoft.com/dynamicsnav:tag

Få Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: elweilando <notifications@github.com>
Sendt: Tuesday, June 11, 2019 8:17:06 AM
Til: microsoft/nav-docker
Cc: Subscribed
Emne: Re: [microsoft/nav-docker] Outdating Containers (#378)


microsoft/dynamics-nav 2018-cu12-fi-ltsc2016 ef54871df619 3 months ago 18.1GB
microsoft/dynamics-nav 2016-cu12-de-ltsc2016 869db40c22bb 3 months ago 16.5GB

**Comment by freddydk** [comment]
Sorry, wrong reply. In order to run old containers you need to specify -accept_outdated -

Få Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: Freddy Kristiansen
Sendt: Tuesday, June 11, 2019 10:12:08 AM
Til: microsoft/nav-docker; microsoft/nav-docker
Cc: Subscribed
Emne: Re: [microsoft/nav-docker] Outdating Containers (#378)

Use mcr.microsoft.com/dynamicsnav:tag

Få Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: elweilando <notifications@github.com>
Sendt: Tuesday, June 11, 2019 8:17:06 AM
Til: microsoft/nav-docker
Cc: Subscribed
Emne: Re: [microsoft/nav-docker] Outdating Containers (#378)


microsoft/dynamics-nav 2018-cu12-fi-ltsc2016 ef54871df619 3 months ago 18.1GB
microsoft/dynamics-nav 2016-cu12-de-ltsc2016 869db40c22bb 3 months ago 16.5GB

**Comment by elweilando** [comment]
Thank you, that works.
But why is this container outdated? I removed the images bevor from my local machine. Comes the outdated from the microsoft docker repository or are there still come caches on my local machine?

**Comment by freddydk** [comment]
We do not rebuild all 10000 images every month.
I typically rebuild the generic image every 1-2 months and all images are using the latest generic image.
In fact we will likely not rebuild "old" images again - meaning that they will run on old versions of ServerCore - if you want to force a new servercore you will need to use -usegenericimage to specify a generic image to replatform to.
New versions of supported NAV or Business Central will be build on new generic images.
