### ISSUE TITLE
Could not upgrade RDL on Report. Illegal character in path

### ISSUE THREAD

**Issue by elweilando** [microsoft/nav-docker#396]
I create a new empty report. Export to Text and import unmodified again. I receive the error "Could not upgrade RDL on Report. Illegal character in path."
I receive this issue, if I export from C/Side with Docker. If I try to import the Textfile into a "normal" installation it works.
Even if I export the Textfile from the "normal" installation, the import into docker runs in that "illigal path" issue. Although a import into the normal installation works fine.

Textcompare between the to files show no difference.

Works not with image:microsoft/dynamics-nav:2016-cu12-de
But works with image: microsoft/dynamics-nav:2016-de

How can I fix this?

**Comment by freddydk** [comment]
Hard to help here, where there really is no information to work with.
Please note that container images have moved; https://freddysblog.com/2019/07/14/nav-and-business-central-docker-images-moved-to-microsoft-container-registry/
but that isn't the problem here.
If you have one docker image where things works and another one where it doesn't - it doesn't seem to be related to docker.
It can be:
- The location where you save the report is not shared with the container (don't know if that is needed)
- Wrong version of C/SIDE
- OEM/UTF conversion (fixed issues with this in containerhelper lately)
- process vs. hyperv isolation
- a million other things
In order for me to help - you would need to export files, attach them here and give me the exact steps you use to reproduce the problem (including how you create your container and the full output of creating the container).

**Comment by freddydk** [comment]
Please supply additional information and reopen if a resolution is still needed
