### ISSUE TITLE
Problems with running the Contaier

### ISSUE THREAD

**Issue by megel** [Microsoft/nav-docker#4]
Hi I have have some problems to get the container running.

My command line was:
`docker run -e ACCEPT_EULA=Y -e username=ADMIN -e password=MYPASSWORD -e ClickOnce=Y -h dockerhost navdocker.azurecr.io/dynamics-nav:2017
`

The power shell output:
```
Initializing...
Running Specific Image
Starting Local SQL Server
Using NavUserPassword Authentication
Using Database Connection localhost/ [CRONUS]
Modify NAV Service Tier Config File for Docker
Hostname is dockerhost
Create Self Signed Certificate
Self Signed Certificate Thumbprint 32758B70DAEA31CAE4FCBBB22597611722472A41
Modify NAV Service Tier Config File with Instance Specific Settings
Restart NAV Service Tier
WARNING: Waiting for service '"Microsoft Dynamics NAV Server [NAV]
(MicrosoftDynamicsNavServer$NAV)' to stop...
WARNING: Waiting for service '"Microsoft Dynamics NAV Server [NAV]
(MicrosoftDynamicsNavServer$NAV)' to stop...
WARNING: Waiting for service '"Microsoft Dynamics NAV Server [NAV]
(MicrosoftDynamicsNavServer$NAV)' to stop...
WARNING: Waiting for service '"Microsoft Dynamics NAV Server [NAV]
(MicrosoftDynamicsNavServer$NAV)' to stop...
WARNING: Waiting for service '"Microsoft Dynamics NAV Server [NAV]
(MicrosoftDynamicsNavServer$NAV)' to stop...
WARNING: Waiting for service '"Microsoft Dynamics NAV Server [NAV]
(MicrosoftDynamicsNavServer$NAV)' to stop...
WARNING: Waiting for service '"Microsoft Dynamics NAV Server [NAV]
(MicrosoftDynamicsNavServer$NAV)' to stop...
WARNING: Waiting for service '"Microsoft Dynamics NAV Server [NAV]
(MicrosoftDynamicsNavServer$NAV)' to stop...
WARNING: Waiting for service '"Microsoft Dynamics NAV Server [NAV]
(MicrosoftDynamicsNavServer$NAV)' to stop...
WARNING: Waiting for service '"Microsoft Dynamics NAV Server [NAV]
(MicrosoftDynamicsNavServer$NAV)' to stop...
WARNING: Waiting for service '"Microsoft Dynamics NAV Server [NAV]
(MicrosoftDynamicsNavServer$NAV)' to stop...
WARNING: Waiting for service '"Microsoft Dynamics NAV Server [NAV]
(MicrosoftDynamicsNavServer$NAV)' to stop...
Using CRONUS license file
Create Web Site
Create NAV Web Server Instance
Create http download site
Create ClickOnce Manifest
Get-NAVServerUser : ServerInstance 'MicrosoftDynamicsNavServer$NAV' is not
running.
At C:\Run\SetupNavUsers.ps1:24 char:11
+     if (!(Get-NAVServerUser -ServerInstance NAV | Where-Object { $_.U ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (0:Int32) [Get-NAVServerUser], Nav
   CommandException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$NAV,Microsoft.Dynamic
   s.Nav.Management.Cmdlets.GetNavServerUser
```

**Comment by freddydk** [comment]
Are you running Windows 10 or Windows Server 2016?
If you are running Windows 10 - remove the docker instance you just created:
Docker ps -a
Docker rm <id>
and try again with -m 4G
Also, you don't need to specify the -h parameter - it defaults to the docker id.

**Comment by Koubek** [comment]
I would recommend running the basic scenario. This means no ClickOnce etc., just accepting EULA + eventually specifying the memory limits `-m 4G` as proposed by @freddydk.

To simplify testing you can use (if you want) `--rm` parameter. This will remove the container automatically in case of a failure.

**Comment by megel** [comment]
It works!!!

The option **-m 2G** worked! 

```
PS C:\WINDOWS\system32> docker run -e ACCEPT_EULA=Y -e username=ADMIN -e password=MYPASSWORD -e ClickOnce=Y -m 2G navdoc
ker.azurecr.io/dynamics-nav:2017
Initializing...
Running Specific Image
Starting Local SQL Server
Using NavUserPassword Authentication
Using Database Connection localhost/ [CRONUS]
Modify NAV Service Tier Config File for Docker
Hostname is 00acbf4d5670
Create Self Signed Certificate
Self Signed Certificate Thumbprint 0C25663F6766F4FCAB2A8F5D8BF41FDA1596FFE6
Modify NAV Service Tier Config File with Instance Specific Settings
Restart NAV Service Tier
WARNING: Waiting for service '"Microsoft Dynamics NAV Server [NAV]
(MicrosoftDynamicsNavServer$NAV)' to stop...
Using CRONUS license file
Create Web Site
Create NAV Web Server Instance
Create http download site
Create ClickOnce Manifest
Msg 15118, Level 16, State 1, Server 00ACBF4D5670, Line 1
Password validation failed. The password does not meet Windows policy requirements because it is not complex enough.
WARNING: The password that you entered does not meet the minimum requirements.
It should be at least 8 characters long and contain at least one uppercase
letter, one lowercase letter, and one number.
NAV Admin Username  : ADMIN
NAV Admin Password  : MYPASSWORD
Container IP Address: 172.27.231.175
Container Hostname  : 00acbf4d5670
Web Client          : https://00acbf4d5670/NAV/WebClient/
ClickOnce Manifest  : http://00acbf4d5670:8080/NAV

Files:
http://00acbf4d5670:8080/certificate.cer

Ready for connections!


TimeGenerated : 8/10/2017 9:36:22 AM
EntryType     : Warning
Message       : Server instance: NAV
                Category: Runtime
                ClientSessionId: be295a19-a0aa-4327-a2ee-61c5c14959bf
                ClientActivityId: 7e599082-d408-4b64-9b3d-f3107ce32b2f
                ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
                ServerActivityId: 00000000-0000-0000-0000-000000000000
                EventTime: 08/10/2017 07:36:22
                Message <ii>Dispose SqlConnectionScope in a different thread,
                IsDisposed=False, sessionId=12, database=CRONUS, threadname=,
                ownerThread=10, stacktrace=</ii>
                ProcessId: 2912
                Tag: 00000AD
                ThreadId: 7
                CounterInformation:
```

**Comment by tjaitly1986** [comment]
Hi,

I am getting the below error while installing the docker image, can you please let me know the issue here?

PS C:\Windows\system32> New-NavContainer -containerName TJ365BC3N -accept_eula -alwaysPull -assignPremiumPlan -auth NavUserPassword -doNotExportObjectsToText -enableSymbolLoading -imageName microsoft/bcsandbox -includeCSide -memoryLimit 4G -updateHosts -useBestContainerOS -useSSL
NavContainerHelper is version 0.6.0.9
Host is Microsoft Windows 10 Enterprise - ltsc2019
Docker Client Version is 18.09.2
Docker Server Version is 18.09.2
Pulling image microsoft/bcsandbox:latest-ltsc2019
latest-ltsc2019: Pulling from microsoft/bcsandbox
Using image microsoft/bcsandbox:latest-ltsc2019
Creating Nav container TJ365BC3N
Version: 14.0.29537.31430-W1
Platform: 14.0.29530.31296
Generic Tag: 0.0.9.3
Container OS Version: 10.0.17763.379 (ltsc2019)
Host OS Version: 10.0.17763.437 (ltsc2019)
Using process isolation
Creating container TJ365BC3N from image microsoft/bcsandbox:latest-ltsc2019
27b6a07d45272ddd02624ec847159cd5363dacd5cbdf59b110acd33274aca78a
Waiting for container TJ365BC3N to be ready
Initializing...
Starting Container
Hostname is TJ365BC3N
PublicDnsName is TJ365BC3N
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 69B8EA57EA681F75369276447FC3D0A59F12E450
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Creating http download site
Creating Windows user tj
Setting SA Password and enabling SA
Creating tj as SQL User and add to sysadmin
Creating SUPER user
ServerInstance 'MicrosoftDynamicsNavServer$NAV' is not running.
at <ScriptBlock>, C:\Run\SetupNavUsers.ps1: line 20
at <ScriptBlock>, C:\Run\my\SetupNavUsers.ps1: line 2
at <ScriptBlock>, C:\Run\navstart.ps1: line 174
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Starting Container
Hostname is TJ365BC3N
PublicDnsName is TJ365BC3N
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 69B8EA57EA681F75369276447FC3D0A59F12E450
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Creating http download site
Creating Windows user tj
Setting SA Password and enabling SA
Creating tj as SQL User and add to sysadmin
Creating SUPER user
ServerInstance 'MicrosoftDynamicsNavServer$NAV' is not running.
at <ScriptBlock>, C:\Run\SetupNavUsers.ps1: line 20
at <ScriptBlock>, C:\Run\my\SetupNavUsers.ps1: line 2
at <ScriptBlock>, C:\Run\navstart.ps1: line 174
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container TJ365BC3N failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.0.9\ContainerHandling\Wait-NavContainerReady.ps1:45 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...J365BC3N failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container TJ365BC3N failed


Thanks
TJ

**Comment by megel** [comment]
Maybe the username is too short?

**Comment by freddydk** [comment]
Tried the exact same command on my machine - works fine.
Running process isolation might cause some of your networks policies to be applied and Michaels suggestion might be pointing in the right direciton. Try a more advanced username and password.
But... - please open another issue rather than replying to an old one which might be a totally different topic, thanks. (not with this one - we found you:-))

**Comment by tjaitly1986** [comment]
Sorry, still the same error..

PS C:\Windows\system32> New-NavContainer -containerName TJBC3657N -accept_eula -alwaysPull -assignPremiumPlan -auth NavUserPassword -clickonce -doNotExportObjectsToText -enableSymbolLoading -imageName microsoft/bcsandbox -includeCSide -isolation process -memoryLimit 4G -shortcuts Desktop -updateHosts -useBestContainerOS -useSSL
NavContainerHelper is version 0.6.0.9
Host is Microsoft Windows 10 Enterprise - ltsc2019
Docker Client Version is 18.09.2
Docker Server Version is 18.09.2
Pulling image microsoft/bcsandbox:latest-ltsc2019
latest-ltsc2019: Pulling from microsoft/bcsandbox
Digest: sha256:73d8ff72e35301fd62e43964a66e7a3f25377d5bf88474703c8815e0d535f650
Using image microsoft/bcsandbox:latest-ltsc2019
Creating Nav container TJBC3657N
Version: 14.0.29537.31430-W1
Platform: 14.0.29530.31296
Generic Tag: 0.0.9.3
Container OS Version: 10.0.17763.379 (ltsc2019)
Host OS Version: 10.0.17763.437 (ltsc2019)
Using process isolation
Creating container TJBC3657N from image microsoft/bcsandbox:latest-ltsc2019
56a1786fbcd6d21bc0162ac035130b53a5b8c66450e052ccc7db060f44349351
Waiting for container TJBC3657N to be ready
Initializing...
Starting Container
Hostname is TJBC3657N
PublicDnsName is TJBC3657N
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 6EA881DB2562C3AEA4DB0E0C3B3C14CEBD7F58D0
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Creating http download site
Creating Windows user tushar
Setting SA Password and enabling SA
Creating tushar as SQL User and add to sysadmin
Creating SUPER user
ServerInstance 'MicrosoftDynamicsNavServer$NAV' is not running.
at <ScriptBlock>, C:\Run\SetupNavUsers.ps1: line 20
at <ScriptBlock>, C:\Run\my\SetupNavUsers.ps1: line 2
at <ScriptBlock>, C:\Run\navstart.ps1: line 174
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Starting Container
Hostname is TJBC3657N
PublicDnsName is TJBC3657N
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 6EA881DB2562C3AEA4DB0E0C3B3C14CEBD7F58D0
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Creating http download site
Creating Windows user tushar
Setting SA Password and enabling SA
Creating tushar as SQL User and add to sysadmin
Creating SUPER user
ServerInstance 'MicrosoftDynamicsNavServer$NAV' is not running.
at <ScriptBlock>, C:\Run\SetupNavUsers.ps1: line 20
at <ScriptBlock>, C:\Run\my\SetupNavUsers.ps1: line 2
at <ScriptBlock>, C:\Run\navstart.ps1: line 174
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container TJBC3657N failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.0.9\ContainerHandling\Wait-NavContainerReady.ps1:45 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...JBC3657N failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container TJBC3657N failed

**Comment by freddydk** [comment]
could you run Get-NavContainerEventLog and see if there are any reasons why the Service Tier doesn't start?
Also try to use -isolation hyperv and see whether this changes anything?
