### ISSUE TITLE
Kubernetes compatiblity

### ISSUE THREAD

**Issue by narongschmidt** [microsoft/nav-docker#411]
Hello.

We are developing business central apps using docker containers on a Kubernetes cluster (16 developers, avg. 3 containers per developer and review environment containers per branch. That are 80 containers in total running at the same time). Containers live until branch merge. This is the main reason why we are using Kubernetes.

The current business central images are built with navcontainerhelper in mind (for setup and convenience). Unfortunately it is not possible for us to use navcontainerhelper in a Kubernetes environment, because we can not just run commands inside containers with powershell.

However this issue is not limited to a Kubernetes setting. It also applies to any other container orchestration environment.

It would be great if you could provide different images for different usages e.g. a test image (with test DLLs already setup) and a regular. Or atleast an environment variable like `includeTestDependencies`.

App deployment is not an issue, we managed to do it over dev endpoint.

**Comment by tfenster** [comment]
@narongschmidt we are running a lot of containers, for various reasons without navcontainerhelper. Currently not "productively" with an orchestration engine, but we are in the last stages for a Swarm setup of probably a bit more than 100 containers.

When we do anything covered by navcontainerhelper, we usually are able to quite easily extract the relevant parts. Where are you running into problems?

**Comment by freddydk** [comment]
Thanks Tobias.
The problem here is that we currently have 10000 images in mcr (all versions and loclizations since 2016) - adding more flavours to those will increase the number of containers every time.
Also adding functionality to the containers requires rebuild of all, which is very cumbersome.
This is the primary reason for adding all innovations to containerhelper AND keep containerhelper open source so that people (like Tobias) can see and use what they want/need.
That said, if Tobias and/or you need hooks or other things to make things happen, I am open for discussing these things. Tobias already did contribute with quite a few PRs to the images.

**Comment by lippertmarkus** [comment]
@narongschmidt Now with custom-built images based on artifacts this should be possible. I also created a Helm chart to simplify deployment to Kubernetes if this helps you as well: https://lippertmarkus.com/2020/10/01/deploy-bc-helm/

**Comment by freddydk** [comment]
Thanks - will close this one.
