### ISSUE TITLE
Can't use CustomNavSettings for values with = in them

### ISSUE THREAD

**Issue by ShadowXVII** [microsoft/nav-docker#445]
Due to the split on [this line](https://github.com/microsoft/nav-docker/blob/717027295bbe925fa2703efa05787f015361bcf1/generic/Run/HelperFunctions.ps1#L541) I can't seem to escape or set values in the Service Tier configuration that have an equals in them.

Trying to set `WSFederationLoginEndpoint` -- I need to set this manually, so the AAD stuff isn't going to assist in this example.

I tried escaping the string (`backtick`, and `\`) however `-split` doesn't seem to care about those.

The only other workaround I could see would be to use an `AdditionalSetup.ps1` with the following? Or, adding a specific environment variable for this key (and other URLs?). A generic solution would be ideal.

```
Write-Host "Modifying Service Tier Config File with Custom Settings"
$CustomConfigFile =  Join-Path $ServiceTierFolder "CustomSettings.config"
$CustomConfig = [xml](Get-Content $CustomConfigFile)

$customConfig.SelectSingleNode("//appSettings/add[@key='WSFederationLoginEndpoint']").Value = 'https://login.windows.net/guid/wsfed?wa=wsignin1.0%26wtrealm=realm'
$CustomConfig.Save($CustomConfigFile)

```

**Comment by ShadowXVII** [comment]
Actually, does this line make sense? 
https://github.com/microsoft/nav-docker/blob/ae6dbf21753f890a364ef29bf566b9fcc25de033/generic/Run/SetupConfiguration.ps1#L94
If the value already exists, don't overwrite? I'm struggling to get it to 

I tried using `"--env federationLoginEndpoint=https://login.windows.net/guid/wsfed"` also, but couldn't get it to apply. I would've thought [this](https://github.com/microsoft/nav-docker/blob/ae6dbf21753f890a364ef29bf566b9fcc25de033/generic/Run/SetupVariables.ps1#L195) would've set that correctly.

**Comment by freddydk** [comment]
Correct, there are values that cannot be set through CustomNavSettings, I looked into that a while back and think I remember that a fix would be a breaking change.
Instead, you can override the SetupConfiguration.ps1 file.

-myscripts @( @{ "SetupConfiguration.ps1" = @"
. 'c:\run\SetupConfiguration.ps1'
# use standard NAV PS functions to set customsettings
"@ } )

(didn't test - but this overrides SetupConfiguration.ps1, calls the standard and then you can set your values)

BTW - the line is correct - it is because some versions doesn't have the wsfed setting in customsettings (this code runs for all versions from NAV 2016 to BC 16) and in that case, it shouldn't be set.
