### ISSUE TITLE
Match OnPrem DVD version with Docker

### ISSUE THREAD

**Issue by PleachiM** [microsoft/nav-docker#461]
Hi, 
I know this might not be the best place to ask this but I was not able to figure out which business central container I need to download when I just need the Version installed on the customer side. 
I have a BC14 CU10 DVD with Version 14.0.41143.0 and can not find it in the image repository. 
Can someone give me a hint?

**Comment by freddydk** [comment]
14.0.41143.0 is the platform version number - since multiple app versions might share the same platform version number, we version docker after the app version number, which for cu10 is 14.11.41204 (https://support.microsoft.com/en-us/help/4538887/cumulative-update-10-for-microsoft-dynamics-365-business-central-april)
so, technically you can use 
`mcr.microsoft.com/businesscentral/onprem:14.11.41204.0-dk-ltsc2019
`or just
`mcr.microsoft.com/businesscentral/onprem:1904-cu10-dk-ltsc2019
`
both will give you the danish

**Comment by PleachiM** [comment]
Thank you!
