### ISSUE TITLE
Folders feature doesn't work for Base Images v1.0.2.6+

### ISSUE THREAD

**Issue by lippertmarkus** [microsoft/nav-docker#512]
## Base Image version v1.0.2.5 works

**Build**
```powershell
New-BcImage -artifactUrl (Get-BCArtifactUrl -version 19.3 -storageAccount bcartifacts -type OnPrem -country at) -includeTestToolkit -includePerformanceToolkit -imageName old -licenseFile "<license>" -baseImage "mcr.microsoft.com/businesscentral:10.0.20348.707-1.0.2.5"
```

**Run**
```powershell
docker run --rm -m 10GB -e "folders=c:\run=https://ppishare.blob.core.windows.net/test/dev_main.zip?sp=r&st=2022-05-31T06:56:50Z&se=2022-06-30T14:56:50Z&spr=https&sv=2020-08-04&sr=b&sig=u8Hypb7m4No207Iyg6Ra3oMCIlRUJxZlsSaCRE53eQI%3D" -e accept_eula=y -e accept_outdated=y old:onprem-19.3.34541.35002-at
```
```diff
Setting up folders...
Downloading https://ppishare.blob.core.windows.net/test/dev_main.zip?sp=r&st=2022-05-31T06:56:50Z&se=2022-06-30T14:56:50Z&spr=https&sv=2020-08-04&sr=b&sig=u8Hypb7m4No207Iyg6Ra3oMCIlRUJxZlsSaCRE53eQI%3D to c:\run
Extracting file in temp folder
Moving all extracted files to target folder c:\run
+Setting up folders took 2 seconds
This seems to be a regular service start
Initializing...
Starting Container
...
```

## Base Image version v1.0.2.7 doesn't work

**Build**
```powershell
New-BcImage -artifactUrl (Get-BCArtifactUrl -version 19.3 -storageAccount bcartifacts -type OnPrem -country at) -includeTestToolkit -includePerformanceToolkit -imageName new -licenseFile "<license>" -baseImage "mcr.microsoft.com/businesscentral:10.0.20348.707-1.0.2.7"
```

**Run**
```powershell
docker run --rm -m 10GB -e "folders=c:\run=https://ppishare.blob.core.windows.net/test/dev_main.zip?sp=r&st=2022-05-31T06:56:50Z&se=2022-06-30T14:56:50Z&spr=https&sv=2020-08-04&sr=b&sig=u8Hypb7m4No207Iyg6Ra3oMCIlRUJxZlsSaCRE53eQI%3D" -e accept_eula=y -e accept_outdated=y new:onprem-19.3.34541.35002-at
```
```diff
Setting up folders...
Downloading https://ppishare.blob.core.windows.net/test/dev_main.zip?sp=r&st=2022-05-31T06:56:50Z&se=2022-06-30T14:56:50Z&spr=https&sv=2020-08-04&sr=b&sig=u8Hypb7m4No207Iyg6Ra3oMCIlRUJxZlsSaCRE53eQI%3D to c:\run
Extracting file in temp folder
Moving all extracted files to target folder c:\run
-Cannot create a file when that file already exists.
```

---
`BcContainerHelper version 3.0.10`

**Comment by lippertmarkus** [comment]
@freddydk any feedback on this?

**Comment by freddydk** [comment]
Sorry, didn't see this before going on vacation - will have a look at this.

**Comment by NAVRockClimber** [comment]
@freddydk how is the status on this one?

Until now we had been able to stay on an older the Generic Image version but with the [current changes](https://www.yammer.com/dynamicsnavdev/threads/1866530998501376) you we are forced to update due to no NextMajor container will start anymore or NextMajor-Pipeline will succeed.

As far as I was able to analyze the issue from @lippertmarkus this happens if you download a zip-file that contains a _my_ folder.

I looks to me like like the [condition](https://github.com/microsoft/nav-docker/blob/755468f3a7d87dac163298fc58978c63b5e2ea2f/generic/Run/start.ps1#L98) for the [if-block](https://github.com/microsoft/nav-docker/blob/755468f3a7d87dac163298fc58978c63b5e2ea2f/generic/Run/start.ps1#L109) here is not met and the else-block is executed where [Move-Item](https://github.com/microsoft/nav-docker/blob/755468f3a7d87dac163298fc58978c63b5e2ea2f/generic/Run/start.ps1#L114) will fail due to the folder _c:\run\my_ already exists.

**Comment by NAVRockClimber** [comment]
@freddydk I uploaded a test file for you here: https://glpmtstorage.blob.core.windows.net/cdn/build_main.zip

That one is used in out nextMajor pipelines.

**Comment by freddydk** [comment]
You can try to add this to your new-bccontainer:

`-myscripts @("https://raw.githubusercontent.com/microsoft/nav-docker/master/override/issue512/start.ps1")`

**Comment by NAVRockClimber** [comment]
I tested it and everything looks good so far. The NextMajor containers start regularly and I did not see any side effect on other containers. Will you create a new generic right away or do you have a release cycle?

**Comment by freddydk** [comment]
new generic images created long ago, assuming it was resolved long ago.
