### ISSUE TITLE
Unable to start debugger

### ISSUE THREAD

**Issue by acyvas** [Microsoft/nav-docker#53]
When trying to run "Sessions" from the web client I get following message:
![image](https://user-images.githubusercontent.com/11752827/30538705-e0ce5468-9c77-11e7-93ce-135802946d84.png)

**Comment by freddydk** [comment]
You are not giving us a lot of information to go with here... but I will try anyway
Not sure how you have installed the Windows Client - but it sounds like the service tier is using a certificate for communication, which isn't trusted on the computer on which your Windows Client is installed.
You would need to add the certificate to Local Machine -> Trusted Certification Authorities.

**Comment by acyvas** [comment]
Sorry for lack of details.
I get this message when trying to run sessions page from web client. Now I understand that web client is trying to launch NAV debugger on my workstation rather than Docker. 
When I run debugger from ClickOnce of "C/SIDE Development Environment" everything works fine. 
In order for it to work directly from web client I would need to add certificate, but path of server certificate is not shown when */devpreview container is run. How could I get the path of certificate?

**Comment by freddydk** [comment]
I am pretty sure, that what happens here is that you launch an installed Windows Client and not actually the clickonce installed windows client. (the webclient navigates to dynamicsnav:////something).
You can probably solve this by pointing the dynamicsnav moniker to your clickonce app - but maybe it cannot be resolved unless you install the Windows Client locally.
I don't think the problem is related to docker, but more related to the fact that you have a clickonce installed windows client.
